import Head from "next/head";
import Button from "../components/Button/Button";
import styles from "../styles/Home.module.css";
import DropDown from "./../components/Dropdown/Dropdown";
import InputText from "../components/InputText/InputText";
export default function Home() {
  const cities = [
    { name: "New York", code: "NY" },
    { name: "Rome", code: "RM" },
    { name: "London", code: "LDN" },
    { name: "Istanbul", code: "IST" },
    { name: "Paris", code: "PRS" },
  ];
  const groupedCities = [
    {
      label: "Germany",
      code: "DE",
      items: [
        { label: "Berlin", value: "Berlin" },
        { label: "Frankfurt", value: "Frankfurt" },
        { label: "Hamburg", value: "Hamburg" },
        { label: "Munich", value: "Munich" },
      ],
    },
    {
      label: "USA",
      code: "US",
      items: [
        { label: "Chicago", value: "Chicago" },
        { label: "Los Angeles", value: "Los Angeles" },
        { label: "New York", value: "New York" },
        { label: "San Francisco", value: "San Francisco" },
      ],
    },
    {
      label: "Japan",
      code: "JP",
      items: [
        { label: "Kyoto", value: "Kyoto" },
        { label: "Osaka", value: "Osaka" },
        { label: "Tokyo", value: "Tokyo" },
        { label: "Yokohama", value: "Yokohama" },
      ],
    },
  ];
  function handleChange(val) {
    alert(val);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <main className={styles.main}>
        <div style={{ display: "flex" }}>
          <DropDown
            optionLabel="name"
            options={cities}
            placeholder={"select a country"}
          ></DropDown>
          <DropDown
            optionLabel="label"
            options={groupedCities}
            optionGroupLabel="label"
            optionGroupChildren="items"
          ></DropDown>
          <Button
            name={"Primary"}
            disabled={false}
            isLoading={false}
            className={"primary text outline"}
          ></Button>
          <Button
            name={"Secondary"}
            disabled={false}
            isLoading={false}
            className={"secondary text  outline"}
          ></Button>
          <Button
            name={"Success"}
            disabled={false}
            isLoading={false}
            className={"success text"}
          ></Button>
          <Button
            name={"Info"}
            disabled={false}
            isLoading={false}
            className={"info text"}
          ></Button>
          <Button
            name={"Warning"}
            disabled={false}
            isLoading={false}
            className={"warning text"}
          ></Button>

          <Button
            name={"Help"}
            disabled={false}
            isLoading={false}
            className={"help text"}
          ></Button>
          <Button
            name={"Danger"}
            disabled={false}
            isLoading={false}
            className={"danger text"}
          ></Button>
          <Button
            name={"Rounded"}
            disabled={false}
            isLoading={false}
            className={"rounded success"}
          ></Button>

          <Button
            icon="bi bi-search"
            disabled={false}
            isLoading={false}
            className={"iconRounded text outline"}
          ></Button>
          <Button
            icon="bi bi-search"
            name="search"
            disabled={false}
            isLoading={false}
            badges={9}
            className={""}
          ></Button>
        </div>
        <div>
          {" "}
          <InputText></InputText>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
